---
title: "assignment 4 test"
author: "Eleonore Durand, Sam Smith, Jill Wirt"
date: "November 21, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}

#Load packages

library(tidyverse)
library(vcdExtra)
library(car)
library(onewaytests)
library(kableExtra)
library(ggsignif)
library(effsize)
library(xtable)
library(stringr)
#Read in original (untidy) data files

lobster_ab <- read_csv("lobster_size_abundance.csv")
traps<- read_csv("lobster_traps.csv")



```

Other things to do/consider:
1. Boxplots
2. Incorporating absolute differences to talk about for some of the tests
5. Figure captions ALL
5. Graph for #1-- need to make captions, fix legend labels, etc




```{r}

#1. : data wrangling for abundance


#Create tidy DF for just 2017 lobster values
lobster_data <- as.data.frame(lobster_ab) %>% 
  expand.dft(freq="COUNT") %>% 
  filter(YEAR == "2017")

#Create tidy DF.
lobster_tidy<- as.data.frame(lobster_ab) %>% 
  expand.dft(freq="COUNT")  

#Create tidy DF, then create a table that shows means and variances in 2017 
lobster_new <- as.data.frame(lobster_ab) %>% 
  expand.dft(freq="COUNT") %>% 
  filter(YEAR == "2017") %>% 
  group_by(SITE) %>% 
  summarize(
    mean_lobster_size = round(mean(SIZE), 1),
    var_lobster_size=round(var(SIZE)),
    sd_lobster=round(sd(SIZE),1)
  )


#Create an abundance table
lobster_ab_trend <- as.data.frame(lobster_ab) %>% 
  expand.dft(freq="COUNT") %>% 
  count(YEAR, SITE) %>% 
  spread(SITE, n) %>% 
  select(-YEAR)


#Re-name rownames within the table to make it useable for chi-square tests, etc
rownames(lobster_ab_trend)<- c ("2012", "2013", "2014", "2015", "2016", "2017")

#View table
lobster_ab_trend

options(knitr.kable.NA = "-")

#Making the table pretty:

ab_table_pretty <- lobster_ab_trend %>% 
  kable(align= "c", col.names = c("Arroyo Quemado", "Carpinteria", "Isla Vista", "Mohawk Reef", "Naples")) %>% 
  kable_styling(bootstrap_options = c("striped", "hover"),
                full_width = FALSE) %>% 
  add_header_above(c("", "Table 1: Lobster Count at Sites, 2012-2017 "=5), escape= FALSE)

ab_table_pretty


#Creating a graph for lobster abundance
ab_scatter<- as.data.frame(lobster_ab) %>% 
  expand.dft(freq="COUNT") %>% 
  count(YEAR, SITE) %>% 
  ggplot(aes(x= YEAR, y=n)) +
  geom_point() +
  geom_line(aes(color=SITE), size=0.5) +
  theme_classic()+ 
  scale_y_continuous(breaks= seq(0,750, by= 100), expand= c(0,0))+
  labs(x= "Year", y= "Lobster Count")+ # Figure 1 INSERT CAPTION HERE
  scale_color_manual(labels= c("Arroyo Quemado", "Carpinteria", "Isla Vista", "Mohawk", "Naples"), values= c("cornflowerblue", "firebrick4", "darkolivegreen", "lightpink2", "gold1")) +
  ggtitle("Variations in Lobster Abundance, 2012-2017") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(family = "Times New Roman"))
  

#seeing if data is normal
ab_hist <-ggplot(lobster_tidy,aes(x=SIZE)) +
  geom_histogram() +
  facet_wrap(~ SITE)+
  theme_classic()

ab_hist


#All of these, except maybe  Carp, look normally distributed for both the histograms and the qqplots.

ab_qq2 <-ggplot(lobster_tidy,aes(sample=SIZE)) +
  geom_qq() +
  facet_wrap(~ SITE, scale="free")+
  theme_classic()

ab_qq2
ab_scatter

#1, Part 2 (Pressure on )

pressure_tidy<- as.data.frame(traps) %>% 
  expand.dft(freq="TRAPS")

#Pressure table
pressure_trend <- as.data.frame(traps) %>% 
  expand.dft(freq="TRAPS") %>%
  count(YEAR, SITE) %>% 
  spread(SITE, n) %>% 
  select(-YEAR) %>% 
  mutate(IVEE= 0, NAPL=0) %>% #used mutate to show that 2 sites didn't have traps
  select("ABUR", "AHND", "AHND to AQUE", "AQUE", "CARP", "GOLB", "IVEE", "MOHK", "NAPL")

rownames(pressure_trend)<- c ("2012", "2013", "2014", "2015", "2016", "2017")
#adds back in the year as row names

pressure_trend

#Make the table look good #MISSING 3 SITES NAMES!!
options(knitr.kable.NA = "-")
pressure_table_pretty <- pressure_trend %>% 
  kable(align= "c", col.names = c("Arroyo Burro Reef", "Arroyo Hondo Reef", "Arroyo Hondo Reef to Arroyo Quemado Reef", "Arroyo Quemado Reef", "Carpinteria Reef", "Goleta Bay Reef", "Isla Vista Reef", "Mohawk Reef", "Naples Reef")) %>% 
  kable_styling(bootstrap_options = c("striped", "hover"),
                full_width = FALSE) %>% 
  add_header_above(c("", "Table 2: Number of Traps at Sites, 2012-2017 "=9), escape= FALSE)

pressure_table_pretty

pressure_scatter<- as.data.frame(traps) %>% 
  expand.dft(freq="TRAPS") %>% 
  count(YEAR, SITE) %>% 
  ggplot(aes(x= YEAR, y=n)) +
  geom_point() +
  geom_line(aes(color= SITE)) +
  scale_y_continuous(breaks= seq(0,1400, by= 200), expand= c(0,0))+
  theme_classic()+
  labs(x= "Year", y= "Number of traps")+ # Figure 2 INSERT CAPTION HERE
  scale_color_manual(labels= c("Arroyo Burro Reef", "Arroyo Hondo Reef", "Arroyo Hondo Reef to \nArroyo Quemado Reef", "Arroyo Quemado Reef", "Carpinteria Reef", "Goleta Bay Reef", "Isla Vista Reef", "Mohawk Reef", "Naples Reef"), values= c("gold1", "plum3", "chocolate2", "cornflowerblue", "firebrick4", "darkolivegreen", "lightpink2", "darkslategrey")) +
  ggtitle("Lobster Fishing Pressure, 2012-2017") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(family = "Times New Roman"))
  
pressure_scatter


```

```{r ANOVA_table, echo = FALSE, results = 'asis', message = FALSE}

#Problem 2. 

#First- we think we want to do an ANOVA. So, we will do the Levene's Test to test for equal variances.

lobster_levene <-leveneTest(SIZE ~ SITE, data=lobster_data)
lobster_levene

#Result of Levene's test: variances are NOT equal, BUTTTTT largest variance is less than 4times the smallest variance, so we can still do ANOVA. Yay!

#Next step: more prep for showing the ANOVA in our results



#2. Run one-way ANOVA

#ANOVA overview:
#single factor: SITE
#levels of factor: 5
#single variable: SIZE

lobster_aov <- aov(SIZE ~ SITE, data=lobster_data)
summary(lobster_aov)

#post hoc testing- let's do Tukey's HSD.
lobster_ph <- TukeyHSD(lobster_aov)

lobster_ph

#3. Make ANOVA table
options(knitr.kable.NA = "-")

table <- xtable(lobster_aov) %>% 
   kable(align= "c", col.names = c("Df", "Sum Sq", "Mean Sq", "F Value", "Pr(>F)"), digits= 2) %>% 
  kable_styling(bootstrap_options = c("striped", "hover"),
                full_width = FALSE) %>% 
  add_header_above(c("", "Table 3: Mean lobster size ANOVA results summary "=5), escape= FALSE)

 table


#4. Make column graph with error bars and letter differences to show ANOVA results
 
aov_lob_graph <- ggplot(lobster_new, aes( x=SITE, y=mean_lobster_size)) +
  geom_col(fill="coral4", color="royalblue4", width= 0.5) +
  geom_errorbar(aes(ymin= mean_lobster_size-sd_lobster, ymax= mean_lobster_size+sd_lobster), width= 0.3, size=0.8) +
  labs(x = "Site", y= "Average Carapace Length (mm)", title = "Average Carapace Length Across Sites in 2017", width = 100) +
  annotate("text", label= "a,b", x="AQUE", y=90, family = "Times New Roman") +
  annotate("text", label= "b", x="CARP", y=90, family = "Times New Roman") +
  annotate("text", label= "b", x="IVEE", y=90, family = "Times New Roman") +
  annotate("text", label= "a,b", x="MOHK", y=86, family = "Times New Roman") +
  annotate("text", label= "a", x="NAPL", y=93, family = "Times New Roman") +
  scale_x_discrete(expand= c(0,0))+
  scale_x_discrete(labels = str_wrap(c("Arroyo Quemado", "Carpinteria", "Isla Vista", "Mohawk", "Naples"), width = 10)) +
  scale_y_continuous(limits= c(0,100), breaks= seq(0,100, by= 10), expand= c(0,0)) +
  theme_classic()+
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(family = "Times New Roman"))

aov_lob_graph


  
```

```{r}

#Part 3. 
aque12_df <- lobster_tidy %>% 
  filter (YEAR ==2012,SITE== "AQUE") %>% 
  select(YEAR, SIZE)

aque17_df <- lobster_tidy %>% 
  filter (YEAR ==2017,SITE== "AQUE") %>% 
  select(YEAR, SIZE)

f_test <- var.test(aque12_df$SIZE, aque17_df$SIZE)
#variances are equal (retain the null because p= 0.29)
f_test

aque_ttest <- t.test(aque12_df$SIZE, aque17_df$SIZE, var.equal = TRUE)
aque_ttest

#next site: CARP

carp12_df <- lobster_tidy %>% 
  filter (YEAR ==2012,SITE== "CARP") %>% 
  select(YEAR, SIZE)

carp17_df <- lobster_tidy %>% 
  filter (YEAR ==2017,SITE== "CARP") %>% 
  select(YEAR, SIZE)

f_carp <- var.test(carp12_df$SIZE, carp17_df$SIZE)
#variances are equal (retain the null because p= 0.22)
f_carp

carp_ttest <- t.test(carp12_df$SIZE, carp17_df$SIZE, var.equal = TRUE)
carp_ttest

#NEXT SITE: IVEE

ivee12_df <- lobster_tidy %>% 
  filter (YEAR ==2012,SITE== "IVEE") %>% 
  select(YEAR, SIZE)

ivee17_df <- lobster_tidy %>% 
  filter (YEAR ==2017,SITE== "IVEE") %>% 
  select(YEAR, SIZE)

f_ivee <- var.test(ivee12_df$SIZE, ivee17_df$SIZE)
#variances are equal (retain the null because p= 0.31)
f_ivee

ivee_ttest <- t.test(carp12_df$SIZE, carp17_df$SIZE, var.equal = TRUE)
ivee_ttest

# Next SITE: MOHK 

mohk12_df <- lobster_tidy %>% 
  filter (YEAR ==2012,SITE== "MOHK") %>% 
  select(YEAR, SIZE)

size <- mohk12_df$SIZE

sd(size)

mohk17_df <- lobster_tidy %>% 
  filter (YEAR ==2017,SITE== "MOHK") %>% 
  select(YEAR, SIZE)

size2 <- mohk17_df$SIZE

sd(size2)

f_mohk <- var.test(mohk12_df$SIZE, mohk17_df$SIZE)
#variances are equal (retain the null because p= 0.15)
f_mohk

mohk_ttest <- t.test(mohk12_df$SIZE, mohk17_df$SIZE, var.equal = TRUE)
mohk_ttest
#there is a significant difference 

#find effect size here! is it correct to call the SIZE variable?  
mohawk_eff <- cohen.d(mohk12_df$SIZE, mohk17_df$SIZE)
mohawk_eff

#Last Site: NAPL
napl12_df <- lobster_tidy %>% 
  filter (YEAR ==2012,SITE== "NAPL") %>% 
  select(YEAR, SIZE)

napl17_df <- lobster_tidy %>% 
  filter (YEAR ==2017,SITE== "NAPL") %>% 
  select(YEAR, SIZE)

f_napl <- var.test(napl12_df$SIZE, napl17_df$SIZE)
#variances are equal (retain the null because p= 0.77)
f_napl

napl_ttest <- t.test(napl12_df$SIZE, napl17_df$SIZE, var.equal = TRUE)
napl_ttest 

#to-do list: create grouped column graphs for each site!- Figure 4
library(reshape2)

column_years_twelve_seventeen <- lobster_tidy %>% 
  filter(YEAR == 2012 | YEAR == 2017)

SITE=c("AQUE","CARP","IVEE", "MOHK", "NAPL")
YEAR=c("2012", "2017")


grouped_column <- ggplot(column_years_twelve_seventeen, aes(x = SITE , y = SIZE)) + 
  geom_bar(aes(fill = YEAR), position = "dodge",  stat="identity", show.legend = FALSE)+
  facet_wrap(~YEAR) +
  theme_classic() +
  labs(x = "Site", y = "Carapace Length (mm)", title = "Size of Spiny Lobsters by Site in 2012 and 2017") +
  scale_x_discrete(labels = str_wrap(c("Arroyo Quemado", "Carpinteria", "Isla Vista", "Mohawk", "Naples"), width = 8)) +
  scale_y_continuous(limits= c(0,120), breaks= seq(0,120, by= 20), expand= c(0,0)) +
  theme_classic()+
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(family = "Times New Roman"))
 

grouped_column

#Ideas: 
# A.ANOVA- nope, dont do this. We are only testing by site, so it's two groups exactly

# B. T-tests- yes, do this! We are comparing the two years at each SITE. Then, in the results/discussion, talk about the significant or not-signifcant differences between the MPA sites and the non-MPA sites.

#Note: should run an F-test for each site first!!
# Why? To determine whether or not to run a Student's t-test (equal variances) or a Welch's Two Sample (unequal variances). Remember, the default is Welch's unequal variances, but the Student's T-test is more powerful/robust.
 


```




```{r}

##4. Chi-square test for proportions.

#A. Create a new table (df?) to make yes/no columns for if each lobster is bigger or smaller than the minimum   
#B. Create a contingency table that's "useable" for chi-square tests to compare proportions.
#C. make the contigency table look good to present in paper.
#D. Run the chi-square!

#to-do: make the contigency table look good to present in paper.

legal_size <- lobster_data %>%
    mutate(
     SIZE = case_when(
      SIZE <= 82.6 ~ "Below legal limit", 
      SIZE > 82.6 ~ "Above legal limit"
    )
  ) %>%
  count(SITE, SIZE) %>%
  spread(SIZE, n) %>% 
  select(-SITE)
   

rownames(legal_size)<- c("AQUE", "CARP", "IVEE", "MOHK", "NAPL")

# B. Make the table look pretty, use kable - Table 4

# C. Make the prop table
prop2_lob <- prop.table (as.matrix(legal_size), 1) 

#D. Run the chi-square test.

lob_x2 <- chisq.test(prop2_lob)
lob_x2

 
```

